wradlib/wradlib

- scripts/install.sh
several packages missing from https://repo.continuum.io/pkgs/free/linux-64/
switching to https://conda.anaconda.org/anaconda
> FIX: use anaconda channel within travis

- .travis.yml
- scripts/install.sh
Explicitly conda install libgdal on Travis CI to insure the latest version of libgdal is install in the conda environment.
closes #26
> Fix GDAL issue on Travis CI

- .travis.yml
- doc/source/release_notes.rst
- setup.py
- wradlib/io.py
- wradlib/util.py
This is the last PR before release of v0.8.0
* checked version, ISRELEASED in setup.py
* fixed some links to wradlib-docs (need to point to latest)
* updated release_notes
closes #6
> Prepare PR for v0.8.0 release

- doc/source/notebooks.rst
- notebooks/radolan.ipynb
- notebooks/radolan_format.ipynb
- notebooks/radolan_grid.ipynb
- notebooks/radolan_network.ipynb
- notebooks/radolan_quickstart.ipynb
- notebooks/radolan_showcase.ipynb
- notebooks/simple_plot.ipynb
This PR adds the former tutorial_radolan_format.rst within the new notebook-section.
It consist of 6 notebooks and shows how the notebooks can be used:
- referencing (also between notebooks and links to api-functions)
- tables
- creation of tocs
- hiding cells
- math, equations
> ENH: convert tutorial_radolan_format.rst to notebook 

- wradlib/georef.py
Solves #63 in module `georef.py`
Changes the `exit()`-calls to `raise ValueError('some sophisticated ErrorString`). This enables the user to at least catch the error and handle it.
> FIX: change exit()-calls to raise

- .travis.yml
- MANIFEST.in
- scripts/convert_notebooks.sh
add notebooks to distribution.
This adds notebooks and the converted python scripts to the `source distribution` (PyPi).
> ENH: copy notebook scripts to examples folder

- wradlib/georef.py
- wradlib/io.py
This adds the FZ product to the radolan composit reader.
This is actually very preliminary. Means the two new header keys will probably be renamed in a future version, when their correct dwd-name is figured out.
This also adds a new grid specification (450 by 450), which wasn't defined before.
> ENH: add reading capability of new radolan FZ product

- wradlib/io.py
DWD sent the format description of the FZ-product.
'VV' - "Vorhersagezeitpunkt" - "prediction time"
'MF' - "Modulflag" - "moduleflag
Also, the data is in RVP6 units like DX and RX. To convert from RVP6 to dBZ:
```python
dbZ = RVP6/2 - 32.5
```
> FIX: incorporate fz-product format description

- doc/source/conf.py
- doc/source/zreferences.rst
Changes the citation label from numbering to alphanumeric, like laid out in #58 
Fixes of all references to in-text citations as follow up PR.
> MIN: add pybtex label plugins to reflect in-text citations more clearly

- .travis.yml
- MANIFEST.in
- setup.py
This fixes the deployment of the converted notebook-scripts alongside the notebooks (`skip_cleanup` needed). Also bumbing build number to actually upload to testpypi.
> MNT: fix deploying converted notebooks, bump build number

- MANIFEST.in
- setup.py
This is another example of a devel release.
We have some changes (adapting MANIFEST.in) and we bumb the MICRO-part of the build number. This will create a devel release on testpypi  after merge.
> MNT: remove *.pyc artefacts from sdist, bump build number

- scripts/install.sh
- wradlib/ipol.py
- wradlib/tests/test_ipol.py
- wradlib/tests/test_util.py
Issue #86 was apparently introduced by a change in behaviour of cKDTree (see also scipy/scipy#6515).
Maximum number of neigbours (nnearest) is now set to maximum number of
source points during runtime. A warning is released in this case.
This change affects ipol.Idw, ipol.OrdinaryKriging and ipol.ExternalDriftKriging.
Akso introduced exceptions in case sources or targets are missing.
> FIX: Addresses issue 86 introduces by scipy 0_18_0.

- setup.py
- wradlib/georef.py
The old approach using `AutoIdentifyEPSG` and `GetAuthorityCode` doesn't work for some reason. Using OGR `IsSame` works fine so far.
> FIX: use OSR  IsSame function to evaluate SRS equality

- notebooks/basics.ipynb
This adds the missing plot notebooks into the basics section of the docs.
> FIX: fix missing notebooks in docs - section

- doc/source/jupyter.rst
- notebooks/visualisation/wradlib_overlay.ipynb
- notebooks/zonalstats/wradlib_zonalstats_quickstart.ipynb
Fixes an issue in wradlib_overlay.ipynb: the Albers projection is not available in gdal 1.10 which we are still using on the Open VM. Used Web Mercator instead.
Fixes an issue in wradlib_zonalstats_quickintro.ipynb: `magma` colormap is only availabel in the latest matplotlib releases. Used `gist_heat` instead.
Minor: Revised the tutorial on how to use jupyter notebooks with conda environments.
> Fixes two issues with older gdal and matplotlib versions.

- notebooks/beamblockage/wradlib_beamblock.ipynb
Otherwise - for some systems such as 32-bit - fantastic problems occur in the final plot of the notebook.
> Define range_res as a float.

- wradlib/io.py
- wradlib/tests/test_georef.py
- wradlib/tests/test_io.py
Not sure if this could be useful for others.
But since I want to work with the different archived RADOLAN files more easily (current `bin.gz` files and historic `tar.gz` files) I added the possibility to pass a file handle to `read_RADOLAN_composite`. This makes it possible to untar and unzip the historic RADOLAN files on the fly and avoids storing uncompressed data or creating temporary files from the tar.gz files. I tried the approach with the temporary files, but this small change to `read_RADOLAN_composite` is much more elegant.
I can however understand that this is just a edge-case and of no use to most other users so that a merge does not make sense.
> Small change so that read_RADOLAN_composite also accepts a file handle

- setup.py
- testrunner.py
- wradlib/qual.py
- wradlib/tests/test_dp.py
We need to take half of the beam width in order to compute the base radius of our cone.
> FIX: Correct error in calculation of pulse volume.

- .coveragerc
- .travis.yml
- scripts/run_tests.sh
- testrunner.py
- wradlib/tests/test_georef.py
- wradlib/tests/test_vis.py
Testing how to make single-notebook-test testsuites running in separate processes with Xvfb on Travis-Ci.
1. With this change, every `unittest.TestSuite` is started in a separate subprocess. 
2. But for the memory consuming notebooks (because of the sheer amount of notebooks) this also breaks the memory limit of travis-ci (all notebooks are run in the same `unittest.TestSuite` / subprocess). So every notebook is started as single `unittest.TestSuite` in a separate process.
3. To get the headless mode with `xvfb` in the subprocesses, we need to export the `DISPLAY` and start `xvfb` before starting the tests.
4. To get `coverage` working with subprocesses, we need to state this in the `.coveragerc`. 
5. To get the correct `exit_status` from `run_test.sh`, we need to retrieve it from the …
> WIP: testrunner fixup

- notebooks/beamblockage/wradlib_beamblock.ipynb
- notebooks/fileio/wradlib_gis_export_example.ipynb
- notebooks/visualisation/wradlib_overlay.ipynb
- wradlib/georef.py
- wradlib/io.py
- wradlib/ipol.py
- wradlib/tests/test_georef.py
- wradlib/tests/test_io.py
- wradlib/tests/test_util.py
- wradlib/util.py
- wradlib/zonalstats.py
This PR handles the issues outline in #135 
new functions
deprecated functions
other fixes
> ENH: Raster handling

- wradlib/io.py
- wradlib/tests/test_io.py
As discussed, [here](https://github.com/cchwala/wradlib/commit/d55678fda5afc9945844f258586d6a47da68e4f3#commitcomment-21557664), this is now the PR to make it possible to read Rainbow files from a file handle, e.g. when reading from a zipped archive.
I assumed that the low level functions do not need the `apichange_kwarg` since nobody ever uses them directly and they only get called by `read_Rainbow`. It would be hard (or impossible without writing to a temp file) to transform the `fid` file handles into the now deprecated `filename` strings because in many cases (or at least in my application) there is no path to the files which e.g. may belong to a zipped archive.
After rebasing on master I cannot run the tests. They fail with "The process has forked and you cannot use this …
> ENH: added option to read rainbow files from file handle

- .travis.yml
- scripts/build_docs.sh
- scripts/convert_notebooks.sh
- scripts/copy_notebooks.sh
- scripts/run_tests.sh
- testrunner.py
Since introduction of the [execute-API](http://nbconvert.readthedocs.io/en/latest/execute_api.html#example) it is possible to execute notebooks within unittests. 
This way we can test the notebooks and in the same time get them rendered.
> MAINT: replace `runipy` workflow by `execute`-API workflow

- wradlib/georef.py
- wradlib/io.py
- wradlib/tests/test_zonalstats.py
- wradlib/zonalstats.py
apply changes to meet [GDAL RFC46](https://trac.osgeo.org/gdal/wiki/rfc46_gdal_ogr_unification).
see #149 
This just replaces `OGR.CreateDataSource()` with `gdal.Create()` as recommended in the linked RFC.
@heistermann
As gdal/ogr related code is constantly added to wradlib codebase in different modules, we should think about a major refactoring. We should concentrate those functions in a dedicated module to avoid circular dependencies among wradlib's modules. The module name could be `wradlib.gdal` (other ideas?).
> WIP: ENH: apply changes to meet GDAL RFC46 

- wradlib/io.py
- wradlib/tests/test_io.py
Add 'QN' header token to RADOLAN reader
closes #153
> FIX: add 'QN' header token to RADOLAN reader

- notebooks/radolan/radolan_grid.ipynb
latex equations in notebooks need to be within two "$" in any case to be properly processed with nbsphinx
closes #161
> FIX: latex equations not displayed

- .travis.yml
- scripts/run_tests.sh
This adds flags to code coverage. Introducing this the combined code coverage as well as the three different tests (doctests, unittests and notebooktests) are shown in the coverage reports.
> ENH: introduce flags to code coverage

- doc/source/gettingstarted.rst
- notebooks/interpolation/wradlib_ipol_example.ipynb
- testrunner.py
As reported in #182 the conda-section in `gettingstarted.rst` is somehow misleading with respect to the cloning of the root environment. This PR removes that part and adds some minor edits to the `GDAL_DATA` treatment.
> FIX: docs clone root

- wradlib/comp.py
In case the quality / weighting grid for the composition are not masked with NaN values outside the radar domain, these areas should be masked based on the radar frids themselves. Otherwise, the resulting weights will be flawed.
> Consider NaNs adequately in weighted composition

- wradlib/io/__init__.py
- wradlib/io/gdal.py
- wradlib/tests/test_io.py
deprecate `open_shape`, add `test_open_vector`, use `gdal.OpenEx`
closes #193
> MIN: add `open_vector` to io.gdal

- wradlib/georef/raster.py
> FIX: use np.array instead of np.stack to be backwards compatible

- doc/source/release_notes.rst
- wradlib/georef/misc.py
- wradlib/tests/test_util.py
- wradlib/util.py
- plus minor change in docstrings in `georef.misc`, closes #216
> FIX: deprecate timeseries functions in `util`

- wradlib/tests/test_zonalstats.py
- wradlib/zonalstats.py
> ENH: add tests to zonalstats

- wradlib/util.py
This change is needed to correctly chain the gdal/ogr Exception stacks. Surfaced with gdal 2.3
> FIX: call gdal,ogr `DontUseExceptions()` in correct order

- wradlib/io/radolan.py
- wradlib/tests/test_io.py
> Add new header token VR.

- scripts/install.sh
- wradlib/__init__.py
- wradlib/io/gdal.py
- wradlib/tests/test_zonalstats.py
- wradlib/zonalstats.py
- add `load_vector`-method to `DataSource`
- enable `ZonalDataBase` to take `DataSource` objects as parameters
- minor change in `io.open_vector`
- adapted tests
- resolves #284
> ENH: enable `ZonalDataBase` to take `DataSource`-object as parameter

- wradlib/adjust.py
This is just a quick fix of a behaviour that breaks cross validation. The overall design of this module is still not optimal with lots of code being repeated in the different `__call__` methods.
> Fix bug in all adjustment classes when checking for None

- wradlib/io/iris.py
- wradlib/tests/test_io.py
- align docstring with actual code and use `sweep`
- do not use `0` for sweep number in docstring
- fix tests
> FIX: align docstring with actual code and use `sweep`

- scripts/install.sh
- wradlib/io/__init__.py
- wradlib/io/xarray.py
- wradlib/tests/test_io.py
This feature makes use of `netcdf`, `h5py` and [xarray](http://xarray.pydata.org/).
It adds readers for:
-  ODIM_H5 and GAMIC hdf5 flavours (can be adapted to other hdf5 source data)
- Cf/Radial1.X flavours
- Cf/Radial2 
The data will be read into a xarray-based structure adhering to the forthcoming Cf/Radial2 standard.
It adds writers for:
- ODIM_H5 
- Cf/Radial2
The data can be written to a netcdf Cf/Radial2 comliant file or to a ODIM_H5 compliant file. This means, that:
- Cf/Radial1 data can be exported to Cf/Radial2 and ODIM_H5
- Cf/Radial2 data can be exported to Cf/Radial2 and ODIM_H5
- ODIM_H5 data can be exported to ODIM_H5 and Cf/Radial2 data
Beside that data format interchange all features of xarray can be exploited. xarray can be extended with `dask` and `cartopy` to gain even …
> ENH: ODIM_H5-Cf/Radial reader/writer

- wradlib/georef/polar.py
- wradlib/tests/test_georef.py
- wradlib/tests/test_verify.py
- wradlib/tests/test_zonalstats.py
This enhances `spherical_to_xyz` to output the resulting data in a more stringent fashion:
The output will be `(theta, phi, r, 3)` meaning that the dimensions of the output data reflect those of input data. 
Two keywords are added:
`squeeze` - if False output dimensions will not be squeezed, future default, if True output dimensions will be squeezed
`strict_dims` - If True, dimensions with the same length, will be treated on their own, if False equal-length dimensions are "combined/merged". Defaults to true in the future.
Here are some examples:
- Version 1:
Input: r (1000), phi (360), theta (0), Output: (1, 360, 1000, 3), Squeezed: (360, 1000, 3)
- Version 2:
Input: r (1000), phi (360), theta (360), Output: (360, 360, 1000, 3), NonStrict: (1, 360, 1000, 3), 
- Version 2b:
Input: r(1000), …
> Fix spherical to xyz

- wradlib/io/xarray.py
Adds .abc in collection to remove warning when importing wradlib.
> MNT: Updates import for MutableMapping from collections to remove warnning. abc was added.

- wradlib/io/radolan.py
I'd like to read a radolan file from stdin but am prevented from the
>  rewind, just in case...
Unfortunately stdin connected to a pipe is not seekable.
Apart from not seekable, if the user pass in a file handle it is his responsibility to position it correctly. The radolan data may not be contained at the start of the file handle.
> Read radolan from piped stdin

- scripts/install.sh
- wradlib/io/xarray.py
This skips NaT values for xarray `to_odim` output generation.
> FIX: skip NaT values to correctly retrieve start and end times

- wradlib/io/radolan.py
- wradlib/tests/test_io.py
- simple xarray wrapper for RADOLAN data
- returns xarray.Dataset with data array as well as coordinates (x, y - polar stereographic projection, time)
- data is transparently decoded using netcdf features (scale_factor, add_offset)
> ENH: minimal xarray wrapper for RADOLAN products

- requirements.txt
v1.5 is missing a dependency in its `requirements.txt`: `requests`
It's being used [here](https://github.com/wradlib/wradlib/blob/847a3c583081747394d0e55494506b815c5af2e3/wradlib/io/dem.py#L26).
> add missing dependency 'requests'

- wradlib/georef/polar.py
Documentation mentions elevation angle in [rads] ,but it should be [deg]. I already discussed in Issue #9.
> Correct error in documentation of sweep_centroids

- wradlib/georef/polar.py
- wradlib/tests/test_clutter.py
- wradlib/tests/test_georef.py
- wradlib/tests/test_io.py
- wradlib/tests/test_ipol.py
> FIX: adapt `georef.polar.sweep_centroids` to only use angles in degrees

- .gitignore
- wradlib/georef/xarray.py
- wradlib/io/xarray.py
1. fix single dimension problem (nrays=ndims)
2. assign root after reading sweeps (moved from @egouden)
done in #395 
3. VolumeTimeSeries class + test (VolTS, with @egouden) 
Test data for 1.& 3. possibly provided by BOM Australia, waiting for feedback
> FIX: single dimension problem

- wradlib/clutter.py
- wradlib/tests/test_clutter.py
There is an error in the logical expression for the low switch in clutter.filter_cloudtype.
It implies that all data are identified as clutter.
Now the cloud types are considered explicitly using equality.
A test has been added to discover this bug.
> FIX: low cloud switch removes everything

- wradlib/tests/test_zr.py
- wradlib/zr.py
This makes `zr.z_to_r_enhanced` capable of handling mutlidimensional arrays. It also uses a convolution sum for creation of shower index (maximizing performance). All other implementations have bee removed.
> ENH: Rework ZR

- wradlib/georef/projection.py
- wradlib/tests/test_georef.py
- wradlib/tests/test_io.py
- remove transform functions, which can simply be replaced by `reproject`, 
- update get_earth_projection to work with model-strings, 
- simplify get_radar_projection
ping @egouden While working towards v1.7 I've cleaned up the projection code a bit. If this is in, I'll try to get in your additions from #380.
> MIN: update projection

- appveyor.yml
- azure-pipelines.yml
- ci/azure/add-conda-to-path.yml
- ci/azure/install.yml
- ci/azure/notebook-tests.yml
- ci/azure/unit-tests.yml
- ci/requirements/py38-notebooks.yml
- ci/requirements/py38.yml
- setup.py
- wradlib/__init__.py
- wradlib/tests/test_vis.py
- wradlib/util.py
- use micromamba on Azure for Linux and OSX builds
- use conda/mamba on Azure for Windows builds
- use conda/mamba on Appveyor
- only use matplotlib-base to not pull in PyQt/Qt 
- update isort to latest release
- fix plot backend issues in tests
> MNT: use micromamba/mamba on Azure, mamba on Appveyor

- .travis.yml
- appveyor.yml
- azure-pipelines.yml
- ci/requirements/py39-notebooks.yml
- ci/requirements/py39.yml
This changes the current build matrix to:
- Azure:
- Python 3.8 and 3.9 Unit Test for Linux, MacOSX and Windows (6)
- Python 3.9 Notebook Tests for Linux, MacOSX and Windows (3)
- Black Style, Flake8 Lint and Isort checks (3)
- Travis:
- Python 3.7 Unit Tests using latest GDAL2 (1)
- Python 3.7, 3.8 and 3.9 Unit Tests using latest GDAL3  (3)
- Python 3.9 Notebook Tests using latest GDAL3 (1)
- Appveyor:
- Python 3.7, 3.8 and 3.9 Unit Tests (3)
I think this is a good compromise between test coverage and CI usage.
> MNT: add Python 3.9 builds to all CI

- wradlib/io/radolan.py
- wradlib/tests/test_io.py
> FIX: add capability to decode old DX header, add test

- wradlib/io/hdf.py
- wradlib/io/xarray.py
- wradlib/tests/test_io_odim.py
This PR fixes two issues:
1. apply correct _FIllValues and lessen tolerance when reindexing odim/gamic arrays
This fixes a bug where data types are wrongly promoted to `float64` when reindexing of arrays is needed. Additionally it fixes problems where reindexing introduces empty rays because of tolerance.
2. correctly unpack gamic hdf5 data
This fixes a longstanding issue whith unpacking GAMIC hdf5 data . The behaviour in wradlib changed from
value = **binvalue / 256** * (dyn_range_max - dyn_range_min) + dyn_range_min (UV8)
value = **binvalue / 65536** * (dyn_range_max - dyn_range_min) + dyn_range_min (UV16)
to 
value = **(binvalue - 1) / 254** * (dyn_range_max - dyn_range_min) + dyn_range_min (UV8)
value = **(binvalue - 1) / 65534** * (dyn_range_max - dyn_range_min) + dyn_range_min …
> FIX: _FillValues and GAMIC dynamic range

- ci/requirements/notebooktests.txt
- ci/requirements/unittests.txt
- requirements.txt
- setup.py
- wradlib/georef/rect.py
- wradlib/io/__init__.py
- wradlib/io/backends.py
- wradlib/io/radolan.py
- wradlib/io/xarray.py
- wradlib/tests/__init__.py
- wradlib/tests/test_io.py
- wradlib/tests/test_io_backends.py
- wradlib/tests/test_io_odim.py
This improves the radolan reader slightly and adds a xarray backend for radolan.
RADOLAN data can be read directly into an xarray dataset like following:
```python
ds = wrl.io.open_radolan_dataset(filename_or_obj)
ds = wrl.io.open_radolan_mfdataset(flist)
ds = xr.open_dataset(filename_or_obj, engine="radolan")
ds = xr.open_mfdataset(flist, engine="radolan")
```
Please note, that for this to work, `xarray>=0.17.0` is needed. For the `mfdataset` functions `dask` is needed too.
Update: This PR also aligns store/open_dataset to the new backend handling
> ENH: add RADOLAN xarray backend, rewrite RADOLAN reader

- setup.py
- wradlib/io/backends.py
- wradlib/io/xarray.py
- wradlib/tests/conftest.py
- wradlib/tests/test_io_backends.py
This PR adds an xarray backend for cfradial, odim and gamic data.
Please note, that for this to work, `xarray>=0.17.0` is needed. For the `mfdataset` functions `dask` is needed too.
ODIM_H5 data can be read directly into an xarray dataset like following:
```python
ds = wrl.io.open_odim_dataset(filename_or_obj)
ds = wrl.io.open_odim_mfdataset(flist)
ds = xr.open_dataset(filename_or_obj, engine="odim", group="dataset1")
ds = xr.open_mfdataset(flist, engine="odim", group="dataset1")
```
GAMIC data can be read directly into an xarray dataset like following:
```python
ds = wrl.io.open_gamic_dataset(filename_or_obj)
ds = wrl.io.open_gamic_mfdataset(flist)
ds = xr.open_dataset(filename_or_obj, engine="gamic", group="scan0")
ds = xr.open_mfdataset(flist, engine="gamic", group="scan0")
``` …
> ENH: add CfRadial, ODIM and GAMIC xarray backends

- wradlib/io/radolan.py
As per the official format description, the HG product uses 4 bytes per pixel (which is, allow me to say, entirely unnecessary - given that it encodes only a handful of different precipitation types...).
https://www.dwd.de/DE/leistungen/radarprodukte/formatbeschreibung_hg.pdf
This MR fixes `wrl.io.radolan.read_radolan_composite` for HG products (from https://opendata.dwd.de/weather/radar/composit/hg/), which was failing with `ValueError: cannot reshape array of size 2640000 into shape (1200,1100)` before.
> Add support for radolan HG product

- wradlib/io/xarray.py
use default values for ODIM/OPERA what-group items if they are not available
Fix already applied to release 1.10 branch as f040ae45c61c925e33f5dadd1a9d829a486a1077
> FIX: use default values for ODIM/OPERA what-group 

- wradlib/georef/rect.py
- wradlib/tests/test_georef.py
- fixes #499 (partly)
- add `mode` kwarg to `wradlib.georef.rect.get_radolan_coordinates`
- add `mode` kwarg to `wradlib.georef.rect.get_radolan_grid`
- default is `mode='radolan'` which returns the lower left corner coordinates (nrows, ncols)
- `mode='center'` returns center coordinates (nrows, ncols)
- `mode='edge'` returns edge coordinates (nrows+1, ncols+1)
> ENH: add `mode`-kwarg to radolan coordinates/grid functions

- wradlib/io/iris.py
- wradlib/tests/test_io.py
- add kwarg `origin`
- add FutureWarning
- add tests
resolves: #493
> ENH: add kwarg `origin` and FutureWarning to IRIS CartesianImage reader

- wradlib/io/backends.py
- wradlib/io/hdf.py
- wradlib/io/xarray.py
- wradlib/tests/test_io.py
- add `reindex_angle` kwarg/backend_kwarg to `open_odim_dataset`/`open_gamic_dataset` readers
- correctly read ODIM_H5 V2.1 angle metadata
- correctly set secondary angle name in `_reindex_angle` -function
closes: #513 and #514
> FIX: odim xarray reader issues

- setup.py
- wradlib/io/backends.py
- wradlib/io/hdf.py
- wradlib/io/iris.py
- wradlib/io/netcdf.py
- wradlib/io/radolan.py
- wradlib/io/xarray.py
- wradlib/tests/test_io.py
- wradlib/tests/test_io_backends.py
This PR covers #361.
- only RAW data files for now
- `open_iris_dataset(filename)`, `open_iris_mfdataset(filename)` - reads sweeps into `RadarVolume`
- `xr.open_dataset(filename, engine="iris", group=1)`, `xr.open_mfdataset(filename, engine="iris", group=1)` reads sweep (group) into `xr.Dataset`
Please refer to function docstring for further explanations.
Update: Fix group numbers, they are int.
> ENH: add iris/sigmet xarray backend

- wradlib/io/backends.py
- wradlib/io/xarray.py
- wradlib/tests/test_io_backends.py
- round fixed decimal to one decimal (as other readers do)
- sortby first dimension in any case
- enhance iris_mapping (add more moments)
- add tests
- add cf-attributes in GAMIC reader
- fix if-clause in open_radar_dataset
- fix regression in legacy GAMIC reader
> ENH: Iris xarray reader, fix GAMIC reader

- LICENSE.txt
- MANIFEST.in
- setup.py
Due to the missing `requirements_optional.txt` in version `1.12.0` and the resulting problems with documentation wradlib 1.13.0 is released in short succession. It's contains essentially the same changes as 1.12.0.
> Rel 1.13.0

- .github/workflows/ci.yml
- ci/requirements/unittests.txt
- requirements_optional.txt
conda-forge migration for Python 3.10 for the wradlib package-stack is finished. Trying to move CI to Python 3.10 for all OS.
> MNT: use Python 3.10 conda-forge everywhere, use cartopy

- wradlib/clutter.py
- wradlib/comp.py
- wradlib/dp.py
- wradlib/georef/misc.py
- wradlib/georef/rect.py
- wradlib/io/backends.py
- wradlib/io/radolan.py
- wradlib/io/rainbow.py
- wradlib/ipol.py
- wradlib/qual.py
- wradlib/tests/test_georef.py
- wradlib/tests/test_io.py
- wradlib/util.py
- wradlib/verify.py
- wradlib/vpr.py
- wradlib/zr.py
This is a fix for #549 . I've added a test for the truncation as well. Put in default argument for datashape = 0, it is only used when looking at the flags (datadepth < 8) and therefore code in the original tests for the radar data itself should remain unaffected.
> Fix zero padding of bits in rainbow format flags (issue 549)

- wradlib/io/xarray.py
- output full timeslice when calling `to_netcdf` with no timestep given
- fix docstring
closes #552
> FIX: output full timeslice when calling `to_netcdf` with no timestep

- wradlib/vpr.py
- use radar site altitude in bin_altitude calculation instead of adding afterwards
closes #546
> FIX: use radar site altitude in bin_altitude calculation

- wradlib/io/xarray.py
> FIX: use start date/time if end date/time is missing for ODIM reader

- .github/workflows/ci.yml
- ci/requirements/notebooktests.yml
- ci/requirements/unittests.yml
- pyproject.toml
- requirements_devel.txt
- setup.py
- wradlib/__init__.py
- wradlib/util.py
This simplifies wradlib's install process in CI as well as the release process. It also removes the dependency to `semver`. In the future we should be able to only use `pyproject.toml` and remove `setup.py` and `setup.cfg`.
> MNT: use pypa's setuptools_scm and build

- ci/requirements/notebooktests.yml
- requirements_optional.txt
- wradlib/georef/projection.py
- wradlib/georef/rect.py
- wradlib/georef/vector.py
- wradlib/io/radolan.py
- wradlib/tests/test_georef.py
- wradlib/tests/test_io.py
- wradlib/tests/test_io_backends.py
- wradlib/tests/test_vpr.py
DWD has recently updated some of their products to use wgs84 ellipsoid instead of sphere as earth model.
This PR:
- add these capabilities
- fixes RADOLAN xarray coordinates (which have been off by 0.5km)
- removes GDAL < 3 compatibility code
> FIX: update DWD grids

- wradlib/io/backends.py
- wradlib/io/radolan.py
- wradlib/tests/test_io.py
This enables "secondary", "cluttermask" and "nodatamask" for xarray datasets in an fully backwards compatible way.
> ENH: add "ancillary"-keyword to io.radolan._radolan_file 

- wradlib/ipol.py
changed np.arange(0,360, 360/data.shape[0]) to np.linspace(0,360,data.shape[0]). Because np.arange changes the shape of the array if the number is even. e.g., if the data is having a shape of 644, 2500 (azis, rngs), and doing np.arange(0, 360, 360.0 / 644).shape will give us the shape 645. This throws then error because it doesn't match with original array and therefore interpolation can't be done.
> Use numpy.linspace in ipol.interpolate_polar

- wradlib/io/misc.py
A bug in the original code in misc.py throws an error when the station being loaded with get_radiosonde() does not have the 'Station identifier' parameter. The problem arises because an iterator of parameters is created and then some transformations are made considering the indexing of the elements of the iterator, under the # read metadata section. When the 'Station identifier' parameter (which is the first element) is missing, the wrong parameter is selected and the error occurs. In this commit, changes in the # read metadata section allow for transforming the set of parameters of metadata referring to the keywords instead of the indexes, in order to avoid the problem of not having the 'Station identifier' parameter.
> Changes in # read metadata under get_radiosonde()

- wradlib/io/backends.py
- wradlib/io/furuno.py
Currently the Furuno Reader isn't capable of ingesting the WR110 (single pol) data. This PR fixes this.
This was reported by Niels Einar Jensen (Furuno DK) via email. Thanks Niels for providing data and manual.
> ENH: read Furuno WR110 (version 103) data

- wradlib/tests/test_georef.py
This xfails another test connected with the download of SRTM data. Obviously there are issues with the BEARER_TOKEN which are hard to investigate.
> Xfail test

- docs/release_notes.md
- wradlib/tests/test_util.py
- wradlib/util.py
Fixed cross_section_ppi  to work with wradlib 2.0
> Fix cross_section_ppi in util.py for wradlib 2.0

- docs/release_notes.md
- wradlib/io/dem.py
- wradlib/vis.py
> FIX: properly implement bearer token authentication and function calling convention for plot_scan_strategy

- docs/release_notes.md
- wradlib/georef/rect.py
- wradlib/io/radolan.py
- wradlib/tests/test_io.py
See https://www.dwd.de/EN/ourservices/radar_products/radar_products.html
PZ is available as binary data file which can be decoded using these enhancements. Beware, that BUFR files which are also available can't be decoded.
Also note, that according DWD -> PZ product might be discontinued in the future.
> ENH: add PZ-product (DWD station product) to RADOLAN reader

- docs/release_notes.md
- wradlib/util.py
The new default value for crs in cross_section_ppi is "None": crs = kwargs.get("crs", "None")
This fixes an issue with the altitude value of the georeferenced object.
> util.py: Update crs default value in cross_section_ppi

- docs/release_notes.md
- wradlib/tests/test_georef.py
Running the tests was not possible on a modest machine with 4GB of RAM running debian 12. It appeared quickly that the memory was growing after each separate test.
After several hours of investigation it seems that it is related to the [caching of fixtures](https://github.com/pytest-dev/pytest/discussions/10387).
This quick fix allows reducing the memory footprint by cleaning manually the most demanding part of the tests.
> FIX manual garbage collector is needed in test with object creation

- docs/release_notes.md
- wradlib/tests/test_util.py
A dataset containing many variables is used in test_cross_session_ppi. This needs more than 1GB of memory.
Using only DBZH significantly reduces the memory footprint of the test.
> ENH use only one data variable for testing

- wradlib/util.py
A dataset with _time_ as dimension (primary coordinate) fails in wradlib.util.dim0 because it expects _azimuth_ or _elevation_.
This quick fix also looks for the _time_ dimension.
> FIX: use time as default dimension

- .github/workflows/ci.yml
This moves the installation from github-based wradlib-data to pypi-based wradlib data.
> MNT: move to pooch base wradlib-data

- .gitignore
* Netcdf files might end up in the project folder when running tests
* `version.py` is autogenerated
Add these in `.gitignore`.
> do not track autogenerated version.py or netcdf files
