wradlib/zonalstats.py

two commits, which are not in wradlib/master

Cherry Pick commits

---

doc/source/community.rst
doc/source/dev_setup.rst
doc/source/gettingstarted.rst
doc/source/recipes.rst
doc/source/release_notes.rst
doc/source/tutorial_radolan_format.rst
doc/source/tutorial_supported_formats.rst
doc/source/tutorial_zonalstats.rst
examples/beamblock_example.py
examples/overlay_example.py
wradlib/io.py
wradlib/util.py

All references to bitbucket are translated to github references

FIX: fix references to bitbucket

---

.travis.yml
LICENSE.txt
MANIFEST.in

TST: test pypi deploy

---

.travis.yml
scripts/install_testing.sh
setup.py

This PR adds a script for just installing wradlib within travis, and install package generating and uploading to pypi. All unittest and doc creation disabled.

TST: further deployment testing

---

.travis.yml

TST: test deploying docs

---

wradlib/io.py
wradlib/tests/test_io.py

This PR resolves issue #31: 
* fixes list reading bug
* adds capability to correctly import rainbow pixmap products

ENH: read pixmap products with rainbow reader

---

README.md
doc/source/dev_setup.rst
doc/source/gettingstarted.rst
doc/source/release_notes.rst
examples/tutorial_zonal_statistics_polar.py

* This fixes the docs regarding the new installation process. It also adapts the latest changes to the release notes.
* This also fixes a minor bug in [tutorial_zonal_statistics_polar.py](https://github.com/wradlib/wradlib/blob/master/examples/tutorial_zonal_statistics_polar.py)
closes #33 closes #34

FIX: docs, minor bug

---

.travis.yml
doc/source/dev_setup.rst
doc/source/gettingstarted.rst
doc/source/refs.bib
doc/source/release_notes.rst
notebooks/attenuation/wradlib_attenuation.ipynb
notebooks/basics/wradlib_get_rainfall.ipynb
notebooks/basics/wradlib_workflow.ipynb
notebooks/beamblockage/wradlib_beamblock.ipynb
notebooks/fileio/wradlib_radar_formats.ipynb
notebooks/fileio/wradlib_reading_dx.ipynb
notebooks/radolan.ipynb
notebooks/radolan/radolan_format.ipynb
notebooks/radolan/radolan_grid.ipynb
notebooks/radolan/radolan_quickstart.ipynb
notebooks/recipes.ipynb
notebooks/visualisation/wradlib_overlay.ipynb
notebooks/visualisation/wradlib_plot_curvelinear_grids.ipynb
notebooks/workflow/recipe1.ipynb
notebooks/zonalstats/wradlib_zonalstats_classes.ipynb
scripts/build_docs.sh

- fixing links in notebooks (inter-notebook and to docs)
- fixing links in docs
- making notebooks in docs pointing to tag version when tagged build

Notebook fixup 2

---

doc/source/ide.rst
doc/source/jupyter.rst
doc/source/notebooks.rst
doc/source/refs.bib
notebooks/basics.ipynb
notebooks/basics/wradlib_get_rainfall.ipynb
notebooks/learnpython.ipynb
notebooks/python/mplintro.ipynb
notebooks/python/numpyintro.ipynb
notebooks/python/quickstart.ipynb
notebooks/python/timeseries.ipynb
notebooks/python/virtenvs.ipynb

Addresses issues #91 and #83 (to a minor extent). 
I think this article is important to make sure users understand and master the transition to notebooks.
Also added a rough layout and some content of a Python intro (issue #92). This intro should guide users to Python issues that we consider as important. This should be further developed in the future.

Article on how to use notebooks plus minor doc edits.

---

.travis.yml
scripts/build_docs.sh
scripts/install.sh
scripts/run_tests.sh

This adds "codecov" as tool for reporting code coverage.
Minor fixes in the build setup.

MAINT: add Codecov

---

scripts/run_tests.sh
testrunner.py

FIX: add subprocess-switch in testrunner.py

---

.coveragerc
scripts/run_tests.sh
testrunner.py

This fixes an issue with test coverage not correctly measured for notebooks.

FIX: fix coverage for notebooks

---

wradlib/zonalstats.py

Will fix conversions if numpy ndarray has multiple Polygons. In this case it will have only one dimension (N,) where every element needs to be treated separately.

FIX: fix `zonalstats.numpy_to_ogr` to handle nested ndarray-cases

---

testrunner.py

This enables `testrunner.py` to take a single string argument. Tests which `TestCase id()` (the name of the test) doesn't contain this argument string are removed from the TestSuites.
Say if you want to test only a specific test-function containing `rvp` you can do it like this:
```bash
(wradlib) user@machine:python testrunner.py -a rvp
rvp2dBZ (wradlib.trafo)
Doctest: wradlib.trafo.rvp2dBZ ... ok
----------------------------------------------------------------------
Ran 1 test in 0.002s
OK
test_rvp2dBZ (test_trafo.TransformationTest) ... ok
----------------------------------------------------------------------
Ran 1 test in 0.000s
OK
```
This makes local testing a lot easier.

ENH: add arg to testrunner.py 

---

wradlib/vis.py

Add altitude offset to plot_rhi

---

wradlib/io/radolan.py
wradlib/tests/test_io.py

Fix read radolan header

---

wradlib/io/iris.py
wradlib/tests/test_io.py

FIX: raise Exception, when file is corrupt (iris-reader)

---

wradlib/vis.py

FIX: correctly calculate azimuth difference

---

wradlib/util.py
wradlib/verify.py

Fixes issue, where doctest output redirect was not resetted correctly

FIX: fix stderr output in util.deprecated doctest, minor doctest fixes

---

setup.py

MAINT: Set `ISRELEASED = False`, bump version number

---

scripts/build_docs.sh

Tests to find the source why the docs aren't pushed to the repo.

WIP: test docs build

---

.travis.yml

FIX: finally cd into `WRADLIB_BUILD_DIR`

---

.travis.yml
scripts/install.sh

as suggested by Travis https://blog.travis-ci.com/2017-12-12-new-trusty-images-q4-launch

FIX: use old image 

---

wradlib/io/iris.py
wradlib/tests/test_io.py
wradlib/util.py

see https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.fromstring.html

FIX: use numpy.frombuffer instead of numpy.fromstring due to deprecation

---

scripts/build_docs.sh
wradlib/ipol.py
wradlib/tests/test_adjust.py
wradlib/tests/test_ipol.py

Fixing dimensions issue in ipol and add tests

---

wradlib/tests/test_util.py
wradlib/util.py

ENH: add tests to `util`

---

wradlib/qual.py
wradlib/tests/test_qual.py
wradlib/vpr.py

ENH: add tests to qual

---

wradlib/tests/test_verify.py
wradlib/verify.py

ENH: add tests to `verify`

---

wradlib/tests/test_zr.py
wradlib/zr.py

ENH: add tests to `zr`

---

wradlib/dp.py
wradlib/tests/test_dp.py

ENH: add tests to `dp`

---

wradlib/tests/test_vpr.py
wradlib/vpr.py

ENH: add tests to `vpr`

---

wradlib/ipol.py
wradlib/tests/test_ipol.py

ENH: add tests to `ipol`, fix strings, fix dimension issue

---

wradlib/atten.py
wradlib/tests/test_atten.py

ENH: add tests to `atten`, fix strings, fix issue #240

---

wradlib/adjust.py
wradlib/tests/test_adjust.py

ENH: add tests to `adjust`

---

wradlib/comp.py
wradlib/tests/test_comp.py

ENH: add tests to `comp`

---

wradlib/tests/test_clutter.py

ENH: add tests to `clutter`

---

wradlib/dp.py
wradlib/tests/test_util.py
wradlib/util.py

More to come... so far, this PR contains:
- moving functions from dp to util and add tests

More module revisions

---

wradlib/georef/misc.py
wradlib/georef/polar.py
wradlib/georef/projection.py
wradlib/georef/raster.py
wradlib/georef/vector.py
wradlib/io/__init__.py
wradlib/io/gdal.py
wradlib/io/hdf.py
wradlib/io/misc.py
wradlib/io/netcdf.py
wradlib/io/radolan.py
wradlib/io/rainbow.py
wradlib/ipol.py
wradlib/tests/test_atten.py
wradlib/tests/test_clutter.py
wradlib/tests/test_comp.py
wradlib/tests/test_io.py
wradlib/tests/test_util.py
wradlib/tests/test_vis.py
wradlib/util.py
wradlib/vis.py
wradlib/vpr.py
wradlib/zonalstats.py

- mostly function names
- resolving minor issues

Mod rework io, georef, vis

---

wradlib/io/hdf.py

FIX: bounding box handling for read_gpm and read_trmm

---

scripts/install.sh
scripts/run_tests.sh
wradlib/ipol.py
wradlib/tests/test_verify.py
wradlib/tests/test_vpr.py
wradlib/verify.py
wradlib/vpr.py

Mainly speeding up the vpr tests and revising docstrings in vpr module.

More module rev

---

wradlib/io/hdf.py

Added this change to hdf.py in io
mask = np.ones_like(lon, dtype=bool,subok=False)
This should fix #273

Add Fix for #273

---

wradlib/vis.py

overplotting of angle ticklabels will be fixed with matplotlib 3

FIX: show angle axis curvelinear grid again

---

wradlib/io/__init__.py
wradlib/io/misc.py
wradlib/tests/test_io.py

- add function to retrieve radiosonde data to `io.misc`, 
- add test

ENH: add function to retrieve radiosonde data 

---

wradlib/__init__.py
wradlib/classify.py
wradlib/io/__init__.py
wradlib/io/misc.py
wradlib/tests/__init__.py
wradlib/tests/test_classify.py
wradlib/tests/test_io.py

WIP: Add 2D HMC

---

requirements_devel.txt
scripts/install.sh
scripts/run_tests.sh

MNT: use pytest framework instead of nose

---

.travis.yml
scripts/install.sh

- adds package caching for conda
- removes unneeded gfortran

ENH: use conda package caching within travis

---

.travis.yml
scripts/install.sh
wradlib/ipol.py
wradlib/util.py
wradlib/vis.py

FIX: fix flake F632

---

wradlib/io/xarray.py

assign coords (azimuth, elevation) for cfradial, fix exception for AttributeError

FIX: coords, AttributeError

---

requirements.txt
scripts/install.sh
setup.py

The development versions need to have the upcoming versions MINOR-Level.
- current stable: 1.2
- current patch: 1.2.1
- upcoming: 1.3.0

MNT: correct use of semver

---

requirements.txt
wradlib/io/__init__.py
wradlib/io/xarray.py
wradlib/tests/test_io.py

This PR cleans-up classes (move static stuff out) and adds xarray to wradlib dependencies.

Odim/CfRadial clean-up

---

.travis.yml
scripts/install.sh
scripts/run_tests.sh

This fixes/adds:
- add `strict` channel preference to conda
- use 2 cores for unittests
- add notebook testsuite

MNT: fix conda, use 2 cores, add notebook testsuite

---

scripts/install.sh
wradlib/io/xarray.py

- fix docstring
- faster conda-env creation

FIX: docstring

---

wradlib/dp.py
wradlib/tests/test_dp.py

- correct nan-handling in texture
- improve performance using numpy views

FIX: correct texture processing

---

wradlib/io/xarray.py

- add keywords for parametrized reading of OdimH5 data, 
- add more OdimH5 moments
closes: #326

ENH: parametrize xarray loading

---

wradlib/io/__init__.py
wradlib/io/iris.py
wradlib/tests/test_io.py

- Implementation of #301 
- Follow up on #180
This is WIP!

ENH: Sigmet redesign

---

wradlib/clutter.py
wradlib/dp.py
wradlib/tests/test_dp.py

- add calculation of `depolarization` ratio to `wradlib.dp`
- enhance/rewrite `wradlib.clutter.classify_echo_fuzzy`

ENH: use dr and cpa in classify_echo_fuzzy 

---

wradlib/clutter.py
wradlib/dp.py
wradlib/georef/polar.py
wradlib/georef/vector.py
wradlib/io/xarray.py
wradlib/tests/test_adjust.py
wradlib/tests/test_atten.py
wradlib/tests/test_georef.py
wradlib/tests/test_io.py
wradlib/tests/test_ipol.py
wradlib/tests/test_util.py
wradlib/tests/test_verify.py
wradlib/tests/test_vis.py
wradlib/tests/test_zonalstats.py
wradlib/vis.py

final additions: docstrings and xarray-hot-fix

MNT: Pre 1.4.0 fixes

---

pyproject.toml
setup.py

- adapt `pyproject.toml` 
- fix setup.py version handling
closes: #335 
Ping: @s-m-e Can you please review this? At least the part with the `pyproject.toml`? I'll pull this in if you approve, but latest the day after tomorrow.

FIX: install time dependencies

---

.gitignore

I have created a `.gitignore` file for this repository based on the GitHub Python.gitignore template. Please let me know if there are any changes you would like for me to make to the file to better serve this project.
closes #339

Create .gitignore file (Issue #339)

---

wradlib/tests/test_util.py
wradlib/util.py

FIX: use `importlib`, correct multidemensional call in `gradient_along_axis`

---

wradlib/zonalstats.py

This PR consist of three different enhancements to speed up processing:
- use temporary files using '/vsimem` to be able to use indexing
- create spatial and attribute index files prior processing
- retrieve attrributes and geometry properties within one function
closes #349

ENH: Speedup ZonalStatistics

---

MANIFEST.in
appveyor.yml
wradlib/tests/test_io.py
wradlib/tests/test_qual.py
wradlib/util.py
wradlib/zonalstats.py

This enables Appveyor as CI and fixes several issues with builds/tests (eg. for windows).

ADD: Appveyor CI 

---

.travis.yml
appveyor.yml
scripts/install.sh

@egouden
This PR just adds the gdal3 build on top of current master. We then can identify the breaking functions and think about how to proceed.

MNT: Add gdal v3 build to travis CI

---

scripts/install.sh

Currently the daily travis `CRON` runs break with an unusual [conda-error](https://travis-ci.org/wradlib/wradlib/jobs/561736109#L1932).
Trying to investigate.

MNT: fix Travis-CI conda handling

---

wradlib/io/xarray.py
wradlib/tests/test_io.py

- apply keywords (eg. for ch…unking, georeferencing)
- introduce two classes for holding open netcdf-file handles (also for properly closing)
- only hold sweep-data in Dataset-dict
- workaround https://github.com/Unidata/netcdf4-python/issues/945
- properly load multiple OdimH5 files into one volume (DWD one sweep one moment files)
- several simplifications

ENH: improve OdimH5- and CfRadial-readers

---

wradlib/georef/raster.py

FIX: set destination projection to destination dataset (fixes #368)

---

wradlib/georef/__init__.py
wradlib/georef/xarray.py
wradlib/io/__init__.py
wradlib/io/xarray.py
wradlib/tests/test_georef.py
wradlib/tests/test_io.py
wradlib/tests/test_vis.py
wradlib/vis.py

- simplify classes
- move out non-class private methods
- remove strict-handling
- make functions private and rename accordingly
- restructure georef-module
- add tests
- add warnings
- keep ['root'] access with DeprecationWarning
- restrict setting of sweep data to class methods
- refactor xarray (georef/io/vis)

WIP: rework Xarray

---

wradlib/georef/xarray.py
wradlib/io/__init__.py
wradlib/io/xarray.py
wradlib/tests/test_georef.py
wradlib/tests/test_io.py
wradlib/vis.py

- add/fix docstrings
- add DeprecationWarning maintaining backwards compatibility for `io.create_xarray_dataarray`
- add `chunks`  keyword to transparently use dask with xarray
- minor fixes

ENH: Finalize xarray

---

wradlib/io/iris.py

- add STATUS product to Iris/Sigmet Reader
- Apply correct decoding of VEL, WIDTH and KDP IrisCartesianProductFile.

ENH: add STATUS product to Iris/Sigmet Reader

---

wradlib/io/xarray.py

See https://github.com/pydata/xarray/issues/3438 and https://github.com/pydata/xarray/pull/3645 for more information

FIX: use xarray.Dataset.rename instead of rename_dims

---

.travis.yml
scripts/install.sh

Test gdal2

---

wradlib/io/xarray.py

Co-authored-by: Edouard Goudenhoofdt <egouden@users.noreply.github.com>
Co-authored-by: Kai Mühlbauer <kmuehlbauer@users.noreply.github.com>
takes over from #407, closes #407

ENH: fix odim moments before merge, if their shape differs

---

appveyor.yml
wradlib/dp.py
wradlib/tests/test_dp.py
wradlib/util.py

- break out derivation code to `util`
- improve derivation itself
- improve NaN - handling

ENH: improve derivation function

---

wradlib/dp.py
wradlib/tests/test_dp.py

Slight improvement in kdp based phase unwrapping:
- takes now parameter th and winlen
- unfolds first phase wrap
- fixes erroneous over-unfold

WIP: ENH: Speedup unfold phi vulpiani

---

wradlib/io/xarray.py
wradlib/tests/test_io_odim.py

- works for GAMIC hdf5
- should work for ODIM_H5 RHI adhering to standard

ENH: read ODIM/GAMIC RHI

---

wradlib/comp.py

FIX: introduce 'call_kwargs' in comp.togrid 

---

wradlib/georef/projection.py
wradlib/tests/test_georef.py

This adds a few projection tools including geoid calculations.

improvement projection

---

wradlib/ipol.py
wradlib/tests/test_ipol.py

ping @egouden 
Implements re-use of binnumbers in RectBin.

ENH: implement re-use of interpolator for RectBin

---

scripts/run_tests.sh
wradlib/tests/__init__.py
wradlib/tests/test_adjust.py
wradlib/tests/test_atten.py
wradlib/tests/test_classify.py
wradlib/tests/test_clutter.py
wradlib/tests/test_comp.py
wradlib/tests/test_dp.py
wradlib/tests/test_georef.py
wradlib/tests/test_io.py
wradlib/tests/test_io_odim.py
wradlib/tests/test_qual.py
wradlib/tests/test_trafo.py
wradlib/tests/test_util.py
wradlib/tests/test_verify.py
wradlib/tests/test_vis.py
wradlib/tests/test_vpr.py
wradlib/tests/test_zonalstats.py
wradlib/tests/test_zr.py

- use pytest for testing, remove unittest
- implement `@require_data` to be able to run tests in case of missing `wradlib-data`
closes #319

MNT: use pytest for testing

---

README.md
azure-pipelines.yml
ci/azure/install.yml
ci/azure/notebook-tests.yml
ci/azure/unit-tests.yml
scripts/run_tests.sh

MNT: enhance ci workflow

---

azure-pipelines.yml
wradlib/io/xarray.py

FIX: always translate ODIM attributes to CF attributes

---

wradlib/tests/test_vis.py
wradlib/vis.py

Co-authored-by: Jorma Rahu <jorahu@users.noreply.github.com>
closes #441

FIX: update `vis.plot_scan_strategy()`

---

wradlib/io/dem.py
wradlib/tests/test_georef.py
wradlib/tests/test_io.py
wradlib/tests/test_vis.py

@egouden FYI: path joining doesn't work for urls (eg. on windows). Had to revert back to simple string joining. 
Added a crude hack iterating over regions to find the correct region if it can't be given by the user...

FIX: fix srtm downloads windows path issues and region selection

---

wradlib/adjust.py
wradlib/classify.py
wradlib/georef/raster.py
wradlib/georef/vector.py
wradlib/io/gdal.py
wradlib/io/iris.py
wradlib/io/misc.py
wradlib/io/rainbow.py
wradlib/io/xarray.py
wradlib/ipol.py
wradlib/tests/test_georef.py
wradlib/tests/test_ipol.py
wradlib/tests/test_vpr.py
wradlib/trafo.py
wradlib/util.py
wradlib/verify.py
wradlib/vis.py
wradlib/zonalstats.py

This fixes some docstring issues and issues with magic trailing comma.

FIX: adapt to new black style checking

---

wradlib/georef/xarray.py

eg. with dataset dimensions of `time`, `azimuth`, `range` where elevation data has (`time`, `azimuth`) dimensions.

FIX: make `georeference_dataset` work with ND datasets

---

wradlib/io/xarray.py

This PR simplifies the internal dimension handling of PPI's/RHI's (azimuth/elevation - dimensions).

Simplify dimension angle handling ODIM/GAMIC

---

setup.py
wradlib/io/hdf.py
wradlib/io/iris.py
wradlib/io/netcdf.py
wradlib/io/radolan.py
wradlib/io/rainbow.py
wradlib/io/xarray.py
wradlib/tests/test_io.py
wradlib/tests/test_io_odim.py
wradlib/util.py

ENH: make wradlib.io capable of consuming file-like objects

---

wradlib/io/iris.py

ENH: decode iris DB_XHDR as numpy structured array

---

wradlib/io/backends.py
wradlib/io/xarray.py

- prefilter angles
- use np.nanmean to calculate final angle resolution for ODIM/GAMIC xarray reader
- update dim0-retrieval
ping @TiemoMathijssen You might test this branch with your data files for correct reading/writing.

FIX: correct calculation of angle resolution in ODIM/GAMIC xarray readers

---

wradlib/vpr.py

- closes: #444 
- fix docstrings
- minor fixes

FIX: remove unnecessary `gridshape` kwarg from docstring in ``CartesianVolume``

---

wradlib/tests/test_vis.py
wradlib/vis.py

- in ``wradlib.vis.plot_scan_strategy``

MIN: correctly handle single/multiple elevations

---

wradlib/io/radolan.py
wradlib/tests/test_io.py

ENH: add %M, %J and %Y RADOLAN products, add test 

---

setup.py
wradlib/atten.py
wradlib/clutter.py
wradlib/georef/polar.py
wradlib/georef/projection.py
wradlib/georef/vector.py
wradlib/io/backends.py
wradlib/io/dem.py
wradlib/io/gdal.py
wradlib/io/hdf.py
wradlib/io/iris.py
wradlib/io/misc.py
wradlib/io/radolan.py
wradlib/io/rainbow.py
wradlib/io/xarray.py
wradlib/io/xarray_depr.py
wradlib/ipol.py
wradlib/tests/test_clutter.py
wradlib/tests/test_georef.py
wradlib/tests/test_io.py
wradlib/tests/test_ipol.py
wradlib/util.py
wradlib/verify.py
wradlib/vis.py
wradlib/vpr.py
wradlib/zonalstats.py

This leads to a better readability in most cases.
- old % style has been replaced completely
- .format() style is kept in place where a template string is used

MNT: use f-strings where appropriate

---

wradlib/clutter.py
wradlib/io/backends.py
wradlib/io/iris.py
wradlib/io/radolan.py
wradlib/io/xarray.py
wradlib/io/xarray_depr.py

use literals `(), [], {}` wherever appropriate

MNT: literals

---

wradlib/georef/raster.py
wradlib/tests/test_georef.py

- raise ValueError if projection cannot be determined from source dataset
- early raise/warn if spacing/size mismatch
- fix docstring
- tests added
closes #551

FIX: raise ValueError if projection cannot be determined from source dataset

---

wradlib/io/xarray.py

FIX: handle variable number of gates in CfRadial1 backend

---

wradlib/io/radolan.py

FIX: take precision into account for RADOLAN WN product

---

wradlib/georef/vector.py
wradlib/io/gdal.py
wradlib/tests/test_georef.py
wradlib/tests/test_io.py
wradlib/tests/test_zonalstats.py
wradlib/zonalstats.py

This PullRequest refactors vector DataSource from zonalstats.DataSource to wradlib.io.gdal.VectorSource.
New Features:
- geopandas connector
- output of features as `numpy.ndarray`. `geopandas.GeoDataFrame` and `OGR.Geometry`
- reprojection on the fly
- context manager (`with wrl.io.VectorSource(file) as vs:`)

zonalstats enhancements

---

ci/requirements/notebooktests.yml
requirements.txt
requirements_optional.txt
wradlib/io/iris.py
wradlib/io/xarray.py
wradlib/io/xarray_depr.py

FIX: correct elevation for negative angles in iris/sigmet RAW data

---

wradlib/clutter.py

adds the default weights and trapezoids in the documentation for each decision variable

Update docstring for classify_echo_fuzzy

---

wradlib/atten.py
wradlib/clutter.py
wradlib/io/backends.py
wradlib/io/dem.py
wradlib/io/xarray.py
wradlib/io/xarray_depr.py
wradlib/ipol.py
wradlib/util.py
wradlib/verify.py
wradlib/vis.py

Changes with respect to new wradlib version to be released before ERAD2022.

Pre Erad2022

---

wradlib/io/dem.py
wradlib/tests/conftest.py
wradlib/tests/test_georef.py
wradlib/tests/test_io.py
wradlib/tests/test_vis.py

MNT: fix SRTM testing if resource is not available, implement timeout

---

wradlib/io/radolan.py
wradlib/io/xarray.py

ASCII files currently not tested.
closes #591
closes #593

WIP: ENH: read RADOLAN ascii format

---

wradlib/clutter.py
wradlib/io/backends.py

This PR adds parametrization to wradlib.clutter.histo_cut and adds description to wradlib xarray backends.
Fixes: #602

Histo cut and xarray backends

---

.github/workflows/ci.yml
ci/requirements/notebooktests.yml
ci/requirements/unittests.yml
wradlib/tests/test_io.py

use mamba-org/setup-micromamba instead of deprecated mamba-org/provision-with-micromamba

MNT: use mamba-org/setup-micromamba 

---

doc/conf.py
doc/installation.md
doc/migration.md
wradlib/adjust.py
wradlib/atten.py
wradlib/classify.py
wradlib/dp.py
wradlib/georef/projection.py
wradlib/georef/raster.py
wradlib/io/__init__.py
wradlib/io/backends.py
wradlib/io/gdal.py
wradlib/io/hdf.py
wradlib/io/iris.py
wradlib/io/netcdf.py
wradlib/io/radolan.py
wradlib/io/rainbow.py
wradlib/ipol.py
wradlib/qual.py
wradlib/util.py
wradlib/verify.py
wradlib/vis.py
wradlib/zonalstats.py

This aligns with https://github.com/wradlib/wradlib-notebooks/pull/87.

DOC: several updates in docstrings

---

docs/release_notes.md
wradlib/georef/polar.py

REGR: make pyproj import lazy

---

docs/release_notes.md
wradlib/georef/misc.py

FIX: use bin_distance-function to calculate xarray-based bin_distance

---

docs/release_notes.md
wradlib/georef/raster.py
wradlib/tests/test_georef.py

See https://github.com/OSGeo/gdal/pull/10003

MNT: Use gdal.Warp instead of deprecated gdal.ReprojectImage

---

docs/release_notes.md
wradlib/io/radolan.py

ENH: open RADOLAN bzip2 compressed files

---

docs/index.md
docs/release_notes.md

ENH: Add note on datamodel on index.md

---

requirements_optional.txt

remove conda packages from requirements_optional.txt

---

docs/release_notes.md
wradlib/comp.py

FIX: make comp.togrid work for Datasets
